### ISSUE TITLE
problème d'affichage 

### ISSUE THREAD

**Issue by Yunus-S** [totomoto/GPI-Fenouil-la-fine-equipe#10]
**Describe the bug**
Tout les bouton de l'accueil sont l'un sur l'autre.

**To Reproduce**
1. Aller sur le site
2. See error

**Expected behavior**
Les bouton devrait être alligné.

**Screenshots**
![image](https://user-images.githubusercontent.com/78805525/114307772-520f8500-9ae1-11eb-8b87-4c4d3f92519d.png)

**Comment by SandricCourant** [comment]
Problème réglé, il fallait utiliser la commande css "float:left" pour tout aligner sur la gauche.
Nouveau design en pièce jointe.
![image](https://user-images.githubusercontent.com/36101178/114433078-aee26c80-9bc1-11eb-9fb2-7c119b18e940.png)
